// Generated 25 Oct 2021 09:21 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MEWeb.Basket
{
    [Serializable]
    public class SubCategoryList
     : SingularBusinessListBase<SubCategoryList, SubCategory>
    {
        #region " Business Methods "

        public SubCategory GetItem(int SubCategoryID)
        {
            foreach (SubCategory child in this)
            {
                if (child.SubCategoryID == SubCategoryID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Sub Categorys";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static SubCategoryList NewSubCategoryList()
        {
            return new SubCategoryList();
        }

        public SubCategoryList()
        {
            // must have parameter-less constructor
        }

        public static SubCategoryList GetSubCategoryList()
        {
            return DataPortal.Fetch<SubCategoryList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(SubCategory.GetSubCategory(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getSubCategoryList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}