// Generated 26 Oct 2021 16:17 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.Product
{
    [Serializable]
    public class CategoryProductList
     : SingularBusinessListBase<CategoryProductList, CategoryProduct>
    {
        #region " Business Methods "

        public CategoryProduct GetItem(int ProductID)
        {
            foreach (CategoryProduct child in this)
            {
                if (child.ProductID == ProductID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Products";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {

          public  int? CategoryID = null;
            public Criteria()
            {
            }
            public Criteria(int? CategoryID)
            {
                CategoryID = CategoryID;
            }
        }

        public static CategoryProductList NewCategoryProductList()
        {
            return new CategoryProductList();
        }

        public CategoryProductList()
        {
            // must have parameter-less constructor
        }

        public static CategoryProductList GetCategoryProductList()
        {
            return DataPortal.Fetch<CategoryProductList>(new Criteria());
        }
        public static CategoryProductList GetCategoryProductList(int CategoryID)
        {
            return DataPortal.Fetch<CategoryProductList>(new Criteria(CategoryID=CategoryID));
        }
        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(CategoryProduct.GetCategoryProduct(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getCategoryProductList";
                        cm.Parameters.AddWithValue("@CategoryID", Singular.Misc.NothingDBNull(crit.CategoryID));
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}