// Generated 17 Nov 2021 07:50 - Singular Systems Object Generator Version 2.2.694
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using System.Data;
using System.Data.SqlClient;


namespace MELib.TempUser
{
    [Serializable]
    public class TempUserList
     : SingularBusinessListBase<TempUserList, TempUser>
    {
        #region " Business Methods "

        public TempUser GetItem(int UserID)
        {
            foreach (TempUser child in this)
            {
                if (child.UserID == UserID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "Users";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static TempUserList NewTempUserList()
        {
            return new TempUserList();
        }

        public TempUserList()
        {
            // must have parameter-less constructor
        }

        public static TempUserList GetTempUserList()
        {
            return DataPortal.Fetch<TempUserList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(TempUser.GetTempUser(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getTempUserList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}